version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  - cmd: git config --global core.autocrlf true
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore --verbosity m
build_script:
  - cmd: dotnet publish ./JsonRocket/JsonRocket.csproj
after_build:
  # For once the build has completed
clone_depth: 1
test_script:
  - cmd: dotnet restore --verbosity m
  - cmd: dotnet test
deploy: off
